module.exports = {
    // 'Original text':'Translated Text'
    common:{

        // forms and validation messages, e.g. "Value of "Name" is: Text"
        'Validation Failed':'Validation Failed',
        'Value of':'Value of',
        'must be':'must be',
        'required':'required',
        'isInteger': 'Number',
        'isString': 'Text',
        'isArray': 'List of Values',
        'isBoolean': 'True or False',
        'minLength': 'Value with Min. Length',
        'maxLength': 'Value with Max. Length',
        'isIn': 'In List of Values',
        'parseDate': 'Date',
        'toDate': 'Date',
        'date': 'Date',
        'toDateString': 'Date',
        'round': 'Number',
        'validate': 'Valid',
        'keyNames': 'Valid',
        'keys': 'Valid',
        'equals': 'is Valid',
        'contains': 'is Valid',
        'matches': 'Valid',
        'isEmail': 'Email',
        'isURL': 'URL',
        'isFQDN': 'FQDN',
        'isIP': 'IP address',
        'isAlpha': 'Letters (a-zA-Z) only',
        'isNumeric': 'Number',
        'isNumber': 'Number',
        'isAlphanumeric': 'Alphanumeric',
        'isBase64': 'Base64',
        'isHexadecimal': 'Hexadecimal',
        'isHexColor': 'Hex Color',
        'isLowercase': 'Lowercase only',
        'isUppercase': 'Uppercase only',
        'isInt': 'Number',
        'isFloat': 'Number',
        'isDivisibleBy': 'Valid',
        'isLength': 'Valid',
        'isByteLength': 'Valid',
        'isUUID': 'UUID',
        'isDate': 'Date',
        'isAfter': 'Later',
        'isBefore': 'Sooner',
        'isCreditCard': 'Credit Card',
        'isISBN': 'ISBN',
        'isJSON': 'JSON',
        'isMultibyte': 'Multibyte',
        'isAscii': 'ASCII chars only',
        'isFullWidth': 'Valid',
        'isHalfWidth': 'Valid',
        'isVariableWidth': 'Valid',
        'isSurrogatePair': 'Surrogate Pair',
        'isPositiveNumber': 'Positive Number',
        'isNegativeNumber': 'Negative Number',
        'isNonPositiveNumber': 'Non Positive Number',
        'isNonNegativeNumber': 'Non Negative Number',
        'isGreaterThan': 'Greater Than',
        'isGreaterOrEqualTo': 'Greater Or Equal',
        'isLowerThan': 'Lower Than',
        'isLowerOrEqualTo': 'Lower Or Equal',
    }
};